---
# tasks file for super-nginx

# Instalaciones
    
    - import_tasks: instalaciones.yml
    
# Configuraciones

    - import_tasks: configuraciones.yml

# Inicio servicios
    
    - import_tasks: inicio_servicios.yml

# COmprobaciones

    - import_tasks: comprobaciones.yml

      # 1 - Organizar las tasks:
      # - Instalaciones
      # - Configuraciones / Post installacion
      # - Inicio Servicios
      # utilizar para ello - import_tasks: instalaciones.yml
      # utilizar para ello - import_tasks: configuraciones.yml ...
      # 2 - Comprobaciones del programa
      # - curl al puerto: texto -> html cuadra con el fichero (texto)
      # - modulo assert
      # 3 - Repositorio como privado
      # 4 - Crear un vaultcon la contraseña de github